.\" Manpage for discovery.
.\" Contact santiago.espinosa14@pm.me to correct errors or typos.
.TH man 8 "12 Aug 2020" "0.3.9-p" "discovery"
.SH NAME
discovery \- Discover online hosts using nmap and ike-scan
.SH SYNOPSIS
discovery [host] <[host]...> <[options]>
.SH DESCRIPTION
discovery is a standalone flat-packed python script that will allow you to automatically scan and detect online hosts. It is compatible with most forms of unix systems and windows. The outputed results are in markdown by default to allow better integration with tools such as pandoc, although it supports outputting in raw JSON to stdout and to a specified output file.
.SH OPTIONS

.IP "-h --help4"
Show help message and exit.

.IP "<targets> or <stdin pipe>"
Space-separated (or newline-separated in the case of stdin input) list of IPs, CIDR IP ranges, or hostnames. All targets are validated and removed if not valid.

.IP "-r --dry-run"
Dry run that displays which hosts would be scanned. Useful if client provides a list with non-valid domains or CIDR range.

.IP -"-i </path/to/file>"
Path to input file with one target per line. Dsicovery will iterate over the lines and scan valid targets. Incompatible with stdin or -t

.IP "-o  --out" </path/to/file>
Path to output file. By default the output will be in JSON with the raw XML output from nmap and stdout from ike-scan

.IP "-r --raw" 
Discovery will output raw json data to stdout/shell as opposed to formatted markdown. Useful if custom nmap commands are used or if further processing of the scans are necessary.

.IP "-q --quick" 
Quick host discovery with fewer scanned ports. Default are 21, 80, 443, 8080, 8888

.IP "-v"
Verbose mode. Will output real-time information and results about the curent running scans.

.IP "--version"
Show the program's version number and exit.

.IP "-vv"
Debug mode. Will output everything in verbose mode plus additional information when processing scan data.



.SH BUGS
No known bugs.
.SH AUTHOR
Santiago Espinosa (santiago.espinosa14@pm.me)